In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

df = pd.read_csv("1000_Companies.csv")
df

     R&D Spend  Administration  Marketing Spend       State        Profit
0    165349.20      136897.800      471784.1000    New York  192261.83000
1    162597.70      151377.590      443898.5300  California  191792.06000
2    153441.51      101145.550      407934.5400     Florida  191050.39000
3    144372.41      118671.850      383199.6200    New York  182901.99000
4    142107.34       91391.770      366168.4200     Florida  166187.94000
..         ...             ...              ...         ...           ...
995   54135.00      118451.999      173232.6695  California   95279.96251
996  134970.00      130390.080      329204.0228  California  164336.60550
997  100275.47      241926.310      227142.8200  California  413956.48000
998  128456.23      321652.140      281692.3200  California  333962.19000
999  161181.72      270939.860      295442.1700    New York  476485.43000

[1000 rows x 5 columns]

In [21]:
# Feature Vector
X = df.iloc[:, :-1].values

# Target Vector
y = df.iloc[:, 4].values


from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# State kolonundaki yazıları sayılara dönüştürme
labelencoder = LabelEncoder()
X[:, 3] = labelencoder.fit_transform(X[:, 3])

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

from sklearn.linear_model import LinearRegression

# Training the model with the training sets we created
model_fit = LinearRegression()
model_fit.fit(X_train, y_train)

y_pred = model_fit.predict(X_test)
y_pred

model_fit.coef_

from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9112595959622047